import path from "path";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { db } from "./client";

export async function migrateIfEnabled() {
  // default ON in production; allow disabling for local quick starts
  if (process.env.DB_MIGRATE === "false") return;

  // this folder must be committed (generated by drizzle-kit)
  const migrationsFolder = path.join(process.cwd(), "drizzle");

  await migrate(db as any, { migrationsFolder });
}